# Generated by Django 5.2 on 2025-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('desc', models.TextField()),
                ('icon', models.ImageField(upload_to='services/icon/%Y/%m/d')),
            ],
        ),
    ]
