# Generated by Django 5.2 on 2025-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='tour_categories/')),
                ('status', models.BooleanField(default=False)),
                ('sale', models.SmallIntegerField(default=0)),
                ('city', models.SmallIntegerField(default=0)),
                ('place', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
