# Generated by Django 5.2 on 2025-05-26 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourcategory',
            name='image',
            field=models.FileField(max_length=200, upload_to='tour_category/'),
        ),
        migrations.AlterField(
            model_name='tourcategory',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
